webapp/news/models.py
from datetime import datetime

from webapp.db import db


class News(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    url = db.Column(db.String, unique=True, nullable=False)
    published = db.Column(db.DateTime, nullable=False)
    text = db.Column(db.Text, nullable=True)

    def coments_count(self):
        return Comment.query.filter(Comment.news_id == self.id).count()

    def __repr__(self):
        return '<News {self.title, self.url}>'


class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.Integer, nullable=False)
    created = db.Column(db.DateTime, nullable=False, default=datetime.now())

    news_id = db.Column(
        db.Integer,
        db.ForeignKey('news.id', ondelete='CASCADE'),
        index=True
        )

    user_id = db.Column(
        db.Integer,
        db.ForeignKey('user.id', ondelete='CASCADE'),
        index=True
    )

    news = db.relationship('News', backref='comments')
    user = db.relationship('User', backref='comments')

    def __repr__(self):
        return '<Comment {}>'.format(self.id)

webapp/news/forms.py
from flask_wtf import FlaskForm
from wtforms import HiddenField, SubmitField, StringField
from wtforms.validators import DataRequired, ValidationError
from flask_login import current_user


class CommentForm(FlaskForm):
    news_id = HiddenField(
        'ID новости',
        validators=[DataRequired()])

    text = StringField(
        'Текст комментария',
        validators=[DataRequired()],
        render_kw={"class": "form-control"})

    submit = SubmitField(
        'Отправить!',
        render_kw={"class": "btn btn-primary"})

    def validate_text(self, text):
        if current_user.is_anonymous:
            raise ValidationError(
                'Зарегистируйтесь, чтобы оставить комментарий')

webapp/news/views.py
from flask import (
    abort,
    Blueprint,
    flash,
    current_app,
    render_template,
    redirect
)
from flask_login import current_user

from webapp.news.models import News, Comment
from webapp.news.forms import CommentForm
from webapp.weather import weather_by_city
from webapp.db import db
from webapp.utils import get_redirect_target

blueprint = Blueprint('news', __name__)


@blueprint.route('/')
def index():
    title = 'Новости Питон'
    weather = weather_by_city(current_app.config['WEATHER_DEFAULT_CITY'])
    news = News.query.filter(News.text.isnot(None)
                             ).order_by(News.published.desc()).all()
    return render_template('news/index.html',
                           page_title=title, weather=weather, news=news)


@blueprint.route('/news/<int:news_id>', methods=['GET', 'POST'])
def single_news(news_id):
    my_news = News.query.filter(News.id == news_id).first()

    if not my_news:
        abort(404)

    form = CommentForm(news_id=my_news.id)

    if form.validate_on_submit():
        comment = Comment(
            news_id=form.news_id.data,
            user_id=current_user.id,
            text=form.text.datas
        )

        db.session.add(comment)
        db.session.commit()
        flash('Комментарий успешно добавлен')
        return redirect(get_redirect_target())
    elif form.errors:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в заполнении поля "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(get_redirect_target())

    return render_template('news/single_news.html', page_title=my_news.title,
                           news=my_news, form=form)

webapp/templates/news/index.html
{% extends 'base.html' %}

{% block content %}
    <div class='row'>

        <div class='col-8'>
        {% include('messages.html') %}

        <h2>Новости</h2>
            {% for new in news %}
                <h3><a href="{{ url_for('news.single_news', news_id=new.id) }}">{{ new.title }}</a></h3>
                <p>{{ new.published.strftime('%d.%m.%Y') }} | Комментарии: {{ new.coments_count() }}</p>
                <hr>
            {% endfor %}
        </div>

        <div class='col-4'>
            <h2>Прогноз погоды</h2>
            {% if weather %}
                Погода: {{ weather.temp_C }}, ощущается как {{ weather.FeelsLikeC }}
            {% else %}
                Сервис погоды временно недоступен
            {% endif %}
        </div>

    </div>
{% endblock %}

webapp/templates/news/single_news.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        <div class="col-8 news-content">
            {% include('messages.html') %}
            {{ news.text|safe }}

            {% if news.comments %}
                <h3>Комментарии:</h3>
                {% for comment in news.comments %}
                <div class="card">
                    <div class="card-body">
                        <p class="card-text">{{ comment.text }}</p>
                        <p class="card-text">
                            <small>Опубликовано: {{ comment.created.strftime('%d.%m.%Y') }} | 
                                Автор: {{ comment.user.username }}</small>
                        </p>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
            <form action="" method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.text.label }}
                    {{ form.text() }}
                </div>
                {{ form.submit() }}
            </form>
            
        </div>
        
        <div class="col-4">

        </div>
    </div>
{% endblock %}