webapp/admin/views.py
from flask import Blueprint, render_template

from webapp.user.decorators import admin_required

blueprint = Blueprint('admin', __name__, url_prefix='/admin')


@blueprint.route('/')
@admin_required
def admin_index():
    title = 'Админ'
    return render_template('admin/index.html', page_title=title)

webapp/news/views.py
from flask import (
    abort,
    Blueprint,
    flash,
    current_app,
    render_template,
    redirect
)
from flask_login import current_user

from webapp.news.models import News, Comment
from webapp.news.forms import CommentForm
from webapp.weather import weather_by_city
from webapp.db import db
from webapp.utils import get_redirect_target

blueprint = Blueprint('news', __name__)


@blueprint.route('/')
def index():
    title = 'Новости Питон'
    weather = weather_by_city(current_app.config['WEATHER_DEFAULT_CITY'])
    news = News.query.filter(News.text.isnot(None)
                             ).order_by(News.published.desc()).all()
    return render_template('news/index.html',
                           page_title=title, weather=weather, news=news)


@blueprint.route('/news/<int:news_id>', methods=['GET', 'POST'])
def single_news(news_id):
    my_news = News.query.filter(News.id == news_id).first()

    if not my_news:
        abort(404)

    form = CommentForm(news_id=my_news.id)

    if form.validate_on_submit():
        comment = Comment(
            news_id=form.news_id.data,
            user_id=current_user.id,
            text=form.text.datas
        )

        db.session.add(comment)
        db.session.commit()
        flash('Комментарий успешно добавлен')
        return redirect(get_redirect_target())
    elif form.errors:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в заполнении поля "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(get_redirect_target())

    return render_template('news/single_news.html', page_title=my_news.title,
                           news=my_news, form=form)

webapp/user/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_user, current_user, logout_user
from werkzeug.urls import url_parse

from webapp.db import db
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from webapp.utils import get_redirect_target

blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    title = 'Авторизация'
    if current_user.is_authenticated:
        return redirect(get_redirect_target())

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if user is None or not user.check_password(form.password.data):
            flash('Не верный логин или пароль')
            return redirect(get_redirect_target())

        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('news.index')

        return redirect(next_page)
    return render_template('user/login.html', page_title=title, form=form)


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('user.login'))


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(get_redirect_target())

    form = RegistrationForm()
    title = 'Регистрация'

    if form.validate_on_submit():
        new_user = User(username=form.username.data,
                        email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Вы успешно зарегистрировались!')
        return redirect(url_for('user.login'))
    elif form.errors:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в поле "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(get_redirect_target())
    return render_template('user/registration.html',
                           page_title=title, form=form)

webapp/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <!-- js highlights -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/atom-one-dark.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

    <title>{{ page_title }}</title>
</head>
<body>
    {% include 'menu.html' %}
    <div class ='container'>
        <h1>{{ page_title }}</h1>
        {% block content %}{% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</body>
</html>

webapp/templates/login.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>{{ page_title }}</title>
</head>
<body>
    <div class ='container'>
    <h1>{{ page_title }}</h1>

    <div class='row'>

        <div class='col-8'>
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                        {{ message }}<br>
                    {% endfor %}
                </div>
                {% endif %}
            {% endwith %}
            <form action="" method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label }}
                    {{ form.username() }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}
                    {{ form.password() }}
                </div>
                {{ form.submit }}
            </form>
        </div>

        <div class='col-4'>

        </div>

    </div>

    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</body>
</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Новости Питона</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('news.index') }}">Главная страница</a>
        </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Искать</button>
    </form>
    <ul class="navbar-nav">

        {% if current_user.is_authenticated %}

                <li class="nav-item">
                  <span class="nav-link" >Привет, {{ current_user.username }}</span>
                </li>

                {% if current_user.is_admin %}
                      <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('admin.admin_index') }}">Админка</a>
                     </li>           
                {% endif %}

                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('user.logout') }}">Выйти</a>
                </li>

        {% else %}

                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('user.register') }}">Зарегистрироваться</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('user.login') }}">Войти</a>
                </li>

        {% endif %}
    </ul>
  </div>
</nav>

webapp/templates/messages.html
{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="alert alert-warning" role="alert">
    {% for message in messages %}
        {{ message }}<br>
    {% endfor %}
</div>
{% endif %}
{% endwith %}